# Generated by Django 3.0.6 on 2020-05-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
