# Generated by Django 3.0.5 on 2020-05-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(verbose_name='Task Creation Time')),
                ('updated_at', models.DateTimeField(verbose_name='Task Last Update Time ')),
                ('due_date', models.DateField(verbose_name='Task Due Date')),
                ('completed_at', models.DateTimeField(verbose_name='Task Completion Time')),
            ],
        ),
    ]
