# Generated by Django 3.0.5 on 2020-05-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='completed_at',
            field=models.DateTimeField(blank=True, verbose_name='Task Completion Time'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(blank=True, verbose_name='Task Due Date'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Task Last Update Time'),
        ),
    ]
