# Generated by Django 3.0.5 on 2020-05-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200513_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='completed_at',
            field=models.DateTimeField(null=True, verbose_name='Task Completion Time'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(null=True, verbose_name='Task Due Date'),
        ),
    ]
