# Generated by Django 3.0.5 on 2020-05-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tasks_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='completed_time',
            new_name='task_completed_time',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='create_time',
            new_name='task_create_time',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='details',
            new_name='task_details',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='due_date',
            new_name='task_due_date',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='last_updated_time',
            new_name='task_last_updated_time',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='status',
            new_name='task_status',
        ),
    ]
