# Generated by Django 3.0.5 on 2020-05-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200514_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_label',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
