# Generated by Django 3.0.5 on 2020-05-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20200515_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=100, verbose_name='Label')),
                ('label_create_time', models.DateTimeField(verbose_name='Label Creation Time')),
                ('label_delete_time', models.DateTimeField(null=True, verbose_name='Label Completion Time')),
            ],
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_category',
            field=models.CharField(max_length=200, null=True, verbose_name='Task Category'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_label',
            field=models.CharField(max_length=200, null=True, verbose_name='Task Label'),
        ),
    ]
