# Generated by Django 3.0.5 on 2020-05-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20200516_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='label_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=100),
        ),
    ]
