# Generated by Django 3.0.6 on 2020-05-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='bio',
            field=models.CharField(default='Please add a profile.', max_length=100, verbose_name='bio'),
        ),
    ]
