# Generated by Django 3.0.6 on 2020-05-21 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_user_profile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
