# Generated by Django 3.0.6 on 2020-05-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20200521_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_hours',
            field=models.IntegerField(default=0, null=True, verbose_name='Task Hours'),
        ),
    ]
