# Generated by Django 3.0.6 on 2020-05-23 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0015_tasks_task_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksHoursLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_time_spent', models.IntegerField(verbose_name='Task Time Spent')),
                ('task_day_of_work', models.DateField(null=True, verbose_name='Task Day of Work')),
                ('task_log_time', models.DateTimeField(null=True, verbose_name='Task Log Time')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Tasks')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
