# Generated by Django 3.0.6 on 2020-05-23 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20200523_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskloghours',
            name='task_day_of_work',
            field=models.DateField(verbose_name='Task Day of Work'),
        ),
        migrations.AlterField(
            model_name='taskloghours',
            name='task_log_notes',
            field=models.CharField(max_length=500, null=True, verbose_name='Task Notes'),
        ),
        migrations.AlterField(
            model_name='taskloghours',
            name='task_log_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Task Log Time'),
            preserve_default=False,
        ),
    ]
