# Generated by Django 3.0.6 on 2020-05-23 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0019_auto_20200523_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_notes', models.CharField(max_length=500, null=True, verbose_name='Task Notes')),
                ('task_note_time', models.DateTimeField(verbose_name='Notes Capture Time')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Tasks')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
