# Generated by Django 3.0.6 on 2020-05-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_tasknotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labels',
            old_name='label_create_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='labels',
            old_name='label_delete_time',
            new_name='delete_time',
        ),
        migrations.RenameField(
            model_name='labels',
            old_name='label_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='labels',
            old_name='label_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='taskloghours',
            old_name='task_day_of_work',
            new_name='day_of_work',
        ),
        migrations.RenameField(
            model_name='taskloghours',
            old_name='task_log_notes',
            new_name='log_notes',
        ),
        migrations.RenameField(
            model_name='taskloghours',
            old_name='task_log_time',
            new_name='log_time',
        ),
        migrations.RenameField(
            model_name='taskloghours',
            old_name='task_time_spent',
            new_name='time_spent',
        ),
        migrations.RenameField(
            model_name='tasknotes',
            old_name='task_note_time',
            new_name='note_time',
        ),
        migrations.RenameField(
            model_name='tasknotes',
            old_name='task_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='task_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='task_completed_time',
            new_name='completed_time',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='task_create_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='task_details',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='task_due_date',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='task_label',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='task_last_updated_time',
            new_name='last_updated_time',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='task_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='task_hours',
        ),
    ]
