# Generated by Django 3.0.6 on 2020-05-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_auto_20200525_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Label Name'),
        ),
    ]
